env: "local"
token_ttl: ""

server:
  port: ":3000"
  timeout: ""

db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  name: "hezzl"
  password: "password"
  ssl_mode: "disable"

redis:
  host: "localhost:6379"
  password: ""
